version: '3.8'

services:
  a:
    build: ./docker-node
    container_name: node-a
    hostname: A
    networks:
      qkd-net:

  b:
    build: ./docker-node
    container_name: node-b
    hostname: B
    networks:
      qkd-net:

  c:
    build: ./docker-node
    container_name: node-c
    hostname: C
    networks:
      qkd-net:


networks:
  qkd-net:
    driver: bridge
